version: '3.8'

services:
  bahana-frontend:
    image: bahana:fe
    container_name: bahana-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - '/app/node_modules'
      - '.:/app'
